/* SPDX-License-Identifier: Apache-2.0 */
package io.justsearch.ort;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.justsearch.configuration.model.ModelPrecision;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Unit tests for the embedded-ONNX-{@code metadata_props} read rung (tempdoc 711 Item 3): a
 * build-time-stamped projection of the manifest's {@code capabilities} section, one priority rung
 * below the manifest itself.
 *
 * <p>Uses two tiny (~150-450 byte) single-node ONNX fixtures committed under {@code
 * src/test/resources/capability-fixtures/} — generated by {@code
 * scripts/models/make_test_fixture.py}, NOT real models. {@code stamped.onnx} carries a fully
 * declared, known {@code io.justsearch.*} metadata_props set; {@code unstamped.onnx} is the
 * identical graph with zero metadata_props, for the "embedded metadata absent" case.
 */
@DisplayName("ModelCapabilityResolver — embedded ONNX metadata_props rung (tempdoc 711 Item 3)")
class ModelCapabilityResolverEmbeddedMetadataTest {

  private static Path fixturesDir;

  @BeforeAll
  static void resolveFixturesDir() throws URISyntaxException {
    URL url =
        ModelCapabilityResolverEmbeddedMetadataTest.class
            .getClassLoader()
            .getResource("capability-fixtures");
    assertNotNull(
        url,
        "capability-fixtures test resources not found on classpath — run"
            + " scripts/models/make_test_fixture.py and commit its output");
    fixturesDir = Path.of(url.toURI());
  }

  @Test
  @DisplayName("embedded metadata_props resolve every fact when the manifest declares none")
  void embeddedMetadataUsedWhenManifestSilent() {
    ModelManifest manifest =
        new ModelManifest(
            "stamped.onnx", "stamped.onnx", null, null, null, ModelManifest.Capabilities.EMPTY);

    ModelCapabilities caps =
        ModelCapabilityResolver.resolve(
            "embedding", fixturesDir, manifest, CapabilityRequirements.EMBEDDING, false);

    assertEquals(ModelCapabilities.PoolingMode.CLS, caps.poolingMode());
    assertEquals(512, caps.trainedContextLength());
    assertEquals(4, caps.embeddingDimension());
    assertEquals(ModelPrecision.FP32, caps.cpuPrecision());
    assertEquals(ModelPrecision.FP16, caps.gpuPrecision());
    assertEquals("search_document: ", caps.documentPrefix());
    assertEquals("search_query: ", caps.queryPrefix());
    assertTrue(
        caps.warnings().isEmpty(),
        "fully declared embedded metadata should produce zero warnings: " + caps.warnings());
  }

  @Test
  @DisplayName("manifest wins on disagreement with embedded metadata, and WARNs naming both values")
  void manifestWinsOnDisagreementWithEmbedded() {
    ModelManifest manifest =
        new ModelManifest(
            "stamped.onnx",
            "stamped.onnx",
            null,
            null,
            null,
            new ModelManifest.Capabilities(
                "mean", 999, 4, "fp32", "fp16", "search_document: ", "search_query: ", null));

    ModelCapabilities caps =
        ModelCapabilityResolver.resolve(
            "embedding", fixturesDir, manifest, CapabilityRequirements.EMBEDDING, false);

    assertEquals(
        ModelCapabilities.PoolingMode.MEAN, caps.poolingMode(), "manifest value must win over embedded 'cls'");
    assertEquals(999, caps.trainedContextLength(), "manifest value must win over embedded 512");
    assertTrue(
        caps.warnings().stream()
            .anyMatch(
                w -> w.contains("pooling_mode disagreement") && w.contains("mean") && w.contains("cls")),
        "pooling_mode disagreement should name both the manifest and embedded values: "
            + caps.warnings());
    assertTrue(
        caps.warnings().stream()
            .anyMatch(
                w -> w.contains("context_length disagreement") && w.contains("999") && w.contains("512")),
        "context_length disagreement should name both the manifest and embedded values: "
            + caps.warnings());
  }

  @Test
  @DisplayName("absence of embedded metadata falls through to the existing rungs unchanged")
  void unstampedModelFallsThroughToExistingRungs() {
    ModelManifest manifest =
        new ModelManifest(
            "unstamped.onnx", null, null, null, null, ModelManifest.Capabilities.EMPTY);

    ModelCapabilities caps =
        ModelCapabilityResolver.resolve(
            "embedding", fixturesDir, manifest, CapabilityRequirements.EMBEDDING, false);

    assertEquals(ModelCapabilities.PoolingMode.UNKNOWN, caps.poolingMode());
    assertEquals(0, caps.trainedContextLength());
    assertEquals(
        4,
        caps.embeddingDimension(),
        "boot-time graph probe (pre-existing rung, unrelated to embedded metadata_props) should"
            + " still resolve dimension from the static output shape");
    assertEquals(
        ModelPrecision.FP32,
        caps.cpuPrecision(),
        "legacy filename-substring heuristic (pre-existing rung) should still apply");
    assertNull(caps.gpuPrecision(), "no gpu variant declared");
    assertNull(caps.documentPrefix());
    assertNull(caps.queryPrefix());
    assertTrue(
        caps.warnings().stream().noneMatch(w -> w.contains("disagreement")),
        "no embedded metadata exists to disagree with: " + caps.warnings());
  }
}
