# Click at window-relative coords in a target window, then capture.
# Usage: click.ps1 -ProcName JustSearch -X 738 -Y 537 -Out after.png
# Thin wrapper over JustSearchGui.psm1. FAILS CLOSED: Invoke-AppClick refuses
# to click (exits 1, no click sent) if the target window did not actually
# take foreground focus -- ported from win-capture.ps1's foreground
# assertion, which this script previously lacked (it clicked blind).
#
# Round 16 (tempdoc 823 section 4): the SAME assertion was missing on the OTHER side
# of the -DelayMs sleep, and that is an evidence-integrity bug, not an
# ergonomics one. With -DelayMs 6000 the round's own terminal reclaimed the
# foreground during the sleep and Save-AppShot (a CopyFromScreen of the
# window RECT) wrote THE TERMINAL'S PIXELS under a health-surface filename --
# precisely the mislabeled-capture class the evidence-review reader gate
# exists to catch, generated by the harness itself. So: the expected
# foreground window is re-asserted immediately before the capture and this
# script exits 1 WITHOUT writing a file on a mismatch. A missing capture is a
# visible gap; a capture of the wrong window is a false claim.
param([string]$ProcName = "JustSearch", [int]$X = 0, [int]$Y = 0, [string]$Out = "after.png", [int]$DelayMs = 2000)
Import-Module (Join-Path $PSScriptRoot "JustSearchGui.psm1") -Force

# Cap checked BEFORE the click, so refusing has no side effect (a cap checked
# after would leave the round with a click it cannot evidence). Round 16's
# retrospective: "never use click.ps1 -DelayMs > ~2500" -- the longer the
# sleep, the likelier something else takes the foreground. For a genuinely
# slow surface, use the documented click-then-separate-capture pattern:
# click.ps1 with a short delay for the ACTION, then a separate
# win-capture.ps1 call for the EVIDENCE frame (win-capture connects and
# focuses immediately before capturing, so it cannot drift).
$maxDelayMs = 3000
if ($DelayMs -gt $maxDelayMs) {
  Write-Output ("DELAY TOO LONG: -DelayMs $DelayMs exceeds the ${maxDelayMs}ms cap (no click sent). " +
    "A long sleep between click and capture is how this script captured the WRONG WINDOW in round 16. " +
    "Use a short -DelayMs for the action and a separate win-capture.ps1 call for the evidence frame.")
  exit 1
}

$conn = Connect-App -ProcName $ProcName -FocusDelayMs 600
if (-not $conn) {
  # Round 11 (tempdoc 805 item 6): this used to print a bare "NO WINDOW" with
  # no process name, so a round that passed a misspelled/wrong -ProcName (the
  # README documents -ProcName, but the durable rule list and instinct both
  # led one round to -Process, which binds anyway via PowerShell's
  # unambiguous-prefix matching -- masking the error until a name that
  # doesn't resolve at all is passed) read the failure as "the installer
  # window is unfindable" instead of "I passed the wrong process name".
  # Echo the ACTUAL $ProcName value that was searched for, not a hardcoded
  # default, so the failure is self-diagnosing.
  Write-Output "NO WINDOW: no top-level window found for process name '$ProcName'"
  exit 1
}

if (-not (Invoke-AppClick -Connection $conn -X $X -Y $Y -SettleDelayMs 250 -ClickHoldMs 80)) {
  exit 1
}

Start-Sleep -Milliseconds $DelayMs

# Re-assert the expected foreground window AFTER the sleep and before the
# capture. Connect-App -Hwnd re-runs the full restore/foreground/ALT-nudge/
# verify path against the SAME hwnd that was clicked (not a fresh -ProcName
# lookup, which could resolve a different window), so a capture is only
# written when the pixels about to be copied really belong to that window.
$verify = Connect-App -Hwnd $conn.Handle -FocusDelayMs 400
if (-not $verify) {
  Write-Output "WINDOW GONE AT CAPTURE TIME: hwnd $($conn.Handle) no longer exists -- refusing to capture (no file written to '$Out')"
  exit 1
}
if (-not $verify.Focused) {
  Write-Output ("FOREGROUND MISMATCH AT CAPTURE TIME: foreground hwnd=$($verify.Foreground) target hwnd=$($conn.Handle) " +
    "after -DelayMs $DelayMs -- refusing to capture (no file written to '$Out'). Something else took the foreground " +
    "during the delay; a capture now would show that window under this filename.")
  exit 1
}

[void](Save-AppShot -Handle $conn.Handle -Out $Out)
