/* SPDX-License-Identifier: Apache-2.0 */
package io.justsearch.ui.api;

import io.javalin.http.Context;
import io.justsearch.configuration.PlatformPaths;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

/**
 * GET /api/governance/state — Layer 4 §4.2 of tempdoc 530.
 *
 * Reads the most recent SARIF run from {@code tmp/governance-report.sarif},
 * projects it to flat JSON, and returns gate verdicts + finding counts.
 *
 * Read-only; doesn't run the gates. Surfaces "discipline debt" to UI
 * consumers alongside indexing / search status.
 *
 * <p>If no SARIF is present, returns {@code {"runs": [], "available": false}}
 * — the gate may simply not have been run yet.
 *
 * <p>Tempdoc 576 §15: alongside the (often-absent) SARIF verdicts, it also serves the COMMITTED,
 * always-present governance projection under {@code "registry"} — the gate roster, exception ceiling,
 * per-seam strength floors, and class-size debt — read verbatim from the {@code governance-state.json}
 * classpath resource (GENERATED by {@code scripts/governance/lib/dashboard.mjs} as a projection of the
 * registry + baselines). One endpoint, one projector; the FE governance dashboard composes it.
 */
public final class GovernanceStateController {
  private static final Logger log = LoggerFactory.getLogger(GovernanceStateController.class);
  private static final String DEFAULT_SARIF_REL = "tmp/governance-report.sarif";
  // Tempdoc 576 §15 — the committed, always-present registry projection (gate roster / exception
  // ceiling / strength floors / class-size debt), generated by scripts/governance/lib/dashboard.mjs.
  private static final String REGISTRY_RESOURCE = "/governance/governance-state.json";
  // Tempdoc 622 §17/§18 — the local-runtime gate-activation history (appended by the gate
  // kernel via scripts/governance/lib/history.mjs). Served the same runtime way as the SARIF;
  // NEVER committed (it is local + dev-skewed). Joined against the committed roster for status.
  private static final String HISTORY_REL = "tmp/governance-history.ndjson";
  // Cap the per-request NDJSON read so an unbounded history stays O(1)-ish (last-N lines).
  private static final int HISTORY_MAX_LINES = 5000;

  private final ObjectMapper mapper = new ObjectMapper();
  private final Path sarifPath;
  private final Path historyPath;

  public GovernanceStateController() {
    // Resolve relative to the project root: the dev runner's CWD is the project
    // root; the SARIF + history paths live under tmp/.
    this(Path.of(DEFAULT_SARIF_REL).toAbsolutePath(), Path.of(HISTORY_REL).toAbsolutePath());
  }

  public GovernanceStateController(Path sarifPath) {
    this(sarifPath, Path.of(HISTORY_REL).toAbsolutePath());
  }

  public GovernanceStateController(Path sarifPath, Path historyPath) {
    this.sarifPath = sarifPath;
    this.historyPath = historyPath;
  }

  public void handle(Context ctx) {
    Map<String, Object> out = new LinkedHashMap<>();
    out.put("source", sarifPath.toString());
    // Tempdoc 576 §15 — the always-present committed projection (independent of whether a SARIF run
    // exists). The FE governance dashboard reads this; live SARIF verdicts (below) are supplementary.
    JsonNode registry = loadRegistryProjection();
    out.put("registry", registry);
    // Tempdoc 622 §17 — local-runtime activation efficacy (which gates ever fire / find anything),
    // joined against the committed roster. Present on every response path; absent-gracefully.
    out.put("efficacy", loadEfficacyProjection(registry));
    if (!Files.exists(sarifPath)) {
      out.put("available", false);
      out.put("gates", List.of());
      ctx.json(out);
      return;
    }
    try {
      JsonNode sarif = mapper.readTree(Files.readAllBytes(sarifPath));
      JsonNode runs = sarif.path("runs");
      List<Map<String, Object>> gates = new ArrayList<>();
      for (JsonNode run : runs) {
        Map<String, Object> g = new LinkedHashMap<>();
        String gateId = run.path("properties").path("categoryId").asText(
            run.path("tool").path("driver").path("name").asText("unknown"));
        g.put("gate", gateId);
        int errors = 0, warnings = 0, notes = 0;
        for (JsonNode result : run.path("results")) {
          String level = result.path("level").asText("note");
          switch (level) {
            case "error" -> errors++;
            case "warning" -> warnings++;
            default -> notes++;
          }
        }
        g.put("verdict", errors == 0 ? "pass" : "fail");
        g.put("errors", errors);
        g.put("warnings", warnings);
        g.put("notes", notes);
        gates.add(g);
      }
      out.put("available", true);
      out.put("modifiedAt", Files.getLastModifiedTime(sarifPath).toInstant().toString());
      out.put("gates", gates);
      ctx.json(out);
    } catch (IOException e) {
      log.warn("Failed to read SARIF at {}: {}", sarifPath, e.getMessage());
      out.put("available", false);
      out.put("error", e.getMessage());
      out.put("gates", List.of());
      ctx.json(out);
    }
  }

  /**
   * The committed registry projection (tempdoc 576 §15), read verbatim from the classpath resource.
   * Returns null when unbundled — the FE degrades to the SARIF-only view.
   */
  private JsonNode loadRegistryProjection() {
    try (var in = GovernanceStateController.class.getResourceAsStream(REGISTRY_RESOURCE)) {
      if (in == null) {
        return null;
      }
      return mapper.readTree(in.readAllBytes());
    } catch (IOException e) {
      log.warn("Failed to read {}: {}", REGISTRY_RESOURCE, e.getMessage());
      return null;
    }
  }

  /**
   * Tempdoc 622 §17 — per-gate activation efficacy, aggregated at request time from the
   * local-runtime {@code tmp/governance-history.ndjson} (NDJSON: {@code {ts, gate, verdict,
   * findings:{error,warning,note}}}). For each gate: total runs, last verdict + timestamp,
   * runs-that-found-something, cumulative finding counts. Joined against the committed roster
   * to assign a {@code status}: {@code active} (runs &gt; 0), {@code never-fired} (in the
   * roster, 0 local runs — NOT necessarily dead; CI/prod runs are not captured), or
   * {@code orphaned} (in history but not the current roster — registry drift).
   *
   * <p>Returns {@code {available:false}} when no history exists (clean checkout) — the FE
   * degrades to the roster-only view. Local + dev-skewed by construction; never committed.
   */
  private Map<String, Object> loadEfficacyProjection(JsonNode registry) {
    Map<String, Object> out = new LinkedHashMap<>();
    if (!Files.exists(historyPath)) {
      out.put("available", false);
      out.put("byGate", List.of());
      return out;
    }
    // Roster gate ids (for never-fired / orphaned classification).
    java.util.Set<String> rosterGates = new java.util.LinkedHashSet<>();
    if (registry != null) {
      for (JsonNode g : registry.path("gates")) {
        rosterGates.add(g.path("id").asText());
      }
    }
    try {
      List<String> lines = Files.readAllLines(historyPath);
      // Cap to the most recent HISTORY_MAX_LINES so an unbounded history stays bounded per request.
      int from = Math.max(0, lines.size() - HISTORY_MAX_LINES);
      Map<String, Map<String, Object>> byGate = new LinkedHashMap<>();
      for (int i = from; i < lines.size(); i++) {
        String line = lines.get(i);
        if (line.isBlank()) {
          continue;
        }
        JsonNode e;
        try {
          e = mapper.readTree(line);
        } catch (tools.jackson.core.JacksonException badLine) {
          continue; // skip malformed NDJSON lines
        }
        String gateId = e.path("gate").asText();
        if (gateId.isEmpty()) {
          continue;
        }
        Map<String, Object> agg = byGate.computeIfAbsent(gateId, k -> {
          Map<String, Object> m = new LinkedHashMap<>();
          m.put("gate", k);
          m.put("totalRuns", 0);
          m.put("runsWithFindings", 0);
          m.put("error", 0);
          m.put("warning", 0);
          m.put("note", 0);
          return m;
        });
        agg.put("totalRuns", (int) agg.get("totalRuns") + 1);
        agg.put("lastVerdict", e.path("verdict").asText());
        agg.put("lastTs", e.path("ts").asText());
        JsonNode f = e.path("findings");
        int err = f.path("error").asInt(0);
        int warn = f.path("warning").asInt(0);
        int note = f.path("note").asInt(0);
        if (err + warn + note > 0) {
          agg.put("runsWithFindings", (int) agg.get("runsWithFindings") + 1);
        }
        agg.put("error", (int) agg.get("error") + err);
        agg.put("warning", (int) agg.get("warning") + warn);
        agg.put("note", (int) agg.get("note") + note);
      }
      // Classify status; include never-fired roster gates (0 local runs).
      List<Map<String, Object>> result = new ArrayList<>();
      for (Map<String, Object> agg : byGate.values()) {
        agg.put("status", rosterGates.contains(agg.get("gate")) ? "active" : "orphaned");
        result.add(agg);
      }
      for (String g : rosterGates) {
        if (!byGate.containsKey(g)) {
          Map<String, Object> m = new LinkedHashMap<>();
          m.put("gate", g);
          m.put("totalRuns", 0);
          m.put("runsWithFindings", 0);
          m.put("error", 0);
          m.put("warning", 0);
          m.put("note", 0);
          m.put("status", "never-fired");
          result.add(m);
        }
      }
      out.put("available", true);
      out.put("scope", "local"); // dev-skewed: CI/prod gate runs are not captured here
      out.put("byGate", result);
      return out;
    } catch (IOException ex) {
      log.warn("Failed to read history at {}: {}", historyPath, ex.getMessage());
      out.put("available", false);
      out.put("byGate", List.of());
      return out;
    }
  }
}
