/* SPDX-License-Identifier: Apache-2.0 */
/*
 * AUTO-GENERATED by scripts/codegen/gen-stream-liveness-constants.mjs (tempdoc 604 PART V/VI).
 *
 * The single source of truth for the LIVE-STREAM SSE heartbeat cadence, shared with the FE
 * re-establishment watchdog (stream-liveness-constants.ts) so producer cadence and consumer window
 * cannot drift. Emitted to BOTH the agent SSE stream (AgentController) and the diagnostic SSE
 * controllers. Do NOT edit by hand (the constant single-authority gate forbids a hand-authored
 * copy); re-generate with:
 *   node scripts/codegen/gen-stream-liveness-constants.mjs
 */
package io.justsearch.ui.api;

/** Generated live-stream liveness constants — see file header. */
public final class StreamLivenessWindows {
  private StreamLivenessWindows() {}

  /** SSE heartbeat cadence: every live SSE stream emits a heartbeat frame at least this often. */
  public static final long STREAM_HEARTBEAT_INTERVAL_MS = 15_000L;

  /** The same cadence in whole seconds, for the {@code scheduleAtFixedRate(..., SECONDS)} callers. */
  public static final long STREAM_HEARTBEAT_INTERVAL_SECONDS = STREAM_HEARTBEAT_INTERVAL_MS / 1000L;
}
