#!/usr/bin/env python3
"""derive_round_plan.py — mechanical brief-to-plan derivation (tempdoc 729-followup).

Problem this closes: a round built its task list from the operator's prose
instead of from the generated coverage-brief.md/coverage-manifest.json, and
one round consequently missed a whole mandatory cohort plus 4 of 5 required
shapes — caught only by luck at finalize. This script converts
coverage-manifest.json's sandbox-tier mustTouch rows into a literal,
per-item checklist a round follows, so the plan is DERIVED from the
authority rather than merely read alongside it.

Reads coverage-manifest.json (the same file gen_coverage_brief.py writes and
check_coverage.py grades against at finalize — see that file's
MustTouchItem schema), NOT coverage-brief.md: the JSON is the stable,
machine-readable schema; scraping the generated Markdown would just add a
second, driftable parser for data that already has one authoritative shape.

Scope: mustTouch items only (cohort/surface/shape, tier=sandbox) — the
concrete failure mode this closes ("missed a whole mandatory cohort plus 4
of 5 required shapes"). mustWatch items (e.g. warm-reinstall-over-existing-
data) are markdown-only in coverage-brief.md and have no equivalent key in
coverage-manifest.json's schema — this script cannot mechanically derive
them and says so explicitly in its output rather than silently omitting
them from the round's awareness.

Pure Python 3 stdlib. No network access.

Usage:
    python derive_round_plan.py --manifest coverage-manifest.json --out round-plan.md
    python derive_round_plan.py --manifest coverage-manifest.json   # prints to stdout
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Mirrors check_coverage.py's MIN_SCREENSHOT_BYTES — kept as a literal here
# (not imported) so this script has no import-time dependency on
# check_coverage.py; if the floor changes there, update this constant too.
MIN_SCREENSHOT_BYTES_HINT = 16384


def load_manifest(path: str) -> dict:
    """Load and return the coverage manifest. Caller handles I/O/JSON errors."""
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def sandbox_must_touch(manifest: dict) -> list[dict]:
    """Every mustTouch row tiered 'sandbox' — the set a round is actually
    required to exercise (matching check_coverage.py's own filter)."""
    items = manifest.get("mustTouch", []) or []
    return [i for i in items if i.get("tier") == "sandbox"]


def shape_token(shape_id: str) -> str:
    """Mirror check_coverage.py's shape_token(): core.rag-ask -> rag-ask."""
    prefix = "core."
    return shape_id[len(prefix):] if shape_id.startswith(prefix) else shape_id


def render_cohort_item(item: dict) -> list[str]:
    lines = [f"- [ ] cohort:{item.get('id', '')}"]
    lines.append(f"      validateHow: {item.get('validateHow', '')}")
    required = item.get("requiredRoutes") or []
    routes = item.get("routes") or []
    if required:
        lines.append(f"      REQUIRED routes (ALL must be hit): {', '.join(required)}")
    elif routes:
        lines.append(f"      any ONE of these routes must be hit: {', '.join(routes)}")
    else:
        lines.append("      (no routes declared on this item — check coverage-manifest.json)")
    lines.append("")
    return lines


def render_surface_item(item: dict) -> list[str]:
    token = item.get("evidenceToken") or ""
    lines = [f"- [ ] surface:{item.get('id', '')}"]
    lines.append(f"      validateHow: {item.get('validateHow', '')}")
    lines.append(
        f"      PROOF: a screenshot whose filename contains `{token}` "
        f"(must be >= {MIN_SCREENSHOT_BYTES_HINT} bytes — check_coverage.py "
        "rejects undersized/near-blank captures)"
    )
    lines.append("")
    return lines


def render_shape_item(item: dict) -> list[str]:
    token = shape_token(item.get("id", ""))
    lines = [f"- [ ] shape:{item.get('id', '')}"]
    lines.append(f"      validateHow: {item.get('validateHow', '')}")
    lines.append(
        f"      PROOF: a screenshot whose filename contains `{token}` "
        f"(must be >= {MIN_SCREENSHOT_BYTES_HINT} bytes — check_coverage.py "
        "rejects undersized/near-blank captures)"
    )
    lines.append("")
    return lines


def render_plan(manifest: dict, manifest_path: str) -> str:
    items = sandbox_must_touch(manifest)
    cohorts = sorted((i for i in items if i.get("kind") == "cohort"), key=lambda i: i.get("id", ""))
    surfaces = sorted((i for i in items if i.get("kind") == "surface"), key=lambda i: i.get("id", ""))
    shapes = sorted((i for i in items if i.get("kind") == "shape"), key=lambda i: i.get("id", ""))

    lines: list[str] = []
    lines.append(
        "<!-- GENERATED by scripts/sandbox/derive_round_plan.py from "
        f"{manifest_path}. This is the round's mechanically-derived task "
        "list -- the SAME manifest check_coverage.py grades against at "
        "finalize. Do not build the round's plan from prose alone; every "
        "item below must be checked off with real evidence before finalize, "
        "or check_coverage.py will fail closed on it. Do not hand-edit -- "
        "regenerate instead. -->"
    )
    lines.append("")
    lines.append("# Sandbox round plan (derived from coverage-manifest.json)")
    lines.append("")
    lines.append(
        f"Sandbox-tier mustTouch items: {len(items)} total "
        f"({len(cohorts)} cohort, {len(surfaces)} surface, {len(shapes)} shape)"
    )
    lines.append("")

    lines.append("## Cohort — prove by hitting the route(s) below (traces.ndjson)")
    lines.append("")
    if cohorts:
        for item in cohorts:
            lines.extend(render_cohort_item(item))
    else:
        lines.append("(none)")
        lines.append("")

    lines.append("## Surface — prove by a screenshot matching the evidence token")
    lines.append("")
    if surfaces:
        for item in surfaces:
            lines.extend(render_surface_item(item))
    else:
        lines.append("(none)")
        lines.append("")

    lines.append("## Shape — prove by a screenshot matching the shape token")
    lines.append("")
    if shapes:
        for item in shapes:
            lines.extend(render_shape_item(item))
    else:
        lines.append("(none)")
        lines.append("")

    covered_elsewhere = manifest.get("coveredElsewhere", []) or []
    exempt = manifest.get("exempt", []) or []
    lines.append("## Not required this round (informational — never graded)")
    lines.append("")
    lines.append(
        f"- coveredElsewhere ({len(covered_elsewhere)}): "
        + (", ".join(f"{e.get('kind', '?')}:{e.get('id', e)}" for e in covered_elsewhere) or "none")
    )
    lines.append(
        f"- exempt ({len(exempt)}): "
        + (", ".join(f"{e.get('kind', '?')}:{e.get('id', e)}" for e in exempt) or "none")
    )
    lines.append("")

    lines.append("## Reminder: must-watch items are NOT on this checklist")
    lines.append("")
    lines.append(
        "This checklist mechanically derives from coverage-manifest.json's "
        "mustTouch rows (cohort/surface/shape) only. coverage-brief.md also "
        "has a 'Must-watch' section (re-injected every round -- e.g. "
        "warm-reinstall-over-existing-data, ui-api-truthfulness-under-load) "
        "that is markdown-only and has no equivalent key in "
        "coverage-manifest.json's schema, so it cannot be mechanically "
        "derived here. Read that section of coverage-brief.md directly -- "
        "it is real required work this checklist cannot enforce."
    )
    lines.append("")

    return "\n".join(lines)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Derive a literal, per-item round-plan checklist from "
            "coverage-manifest.json (tempdoc 729-followup, mechanical "
            "brief-to-plan derivation)."
        )
    )
    parser.add_argument(
        "--manifest",
        required=True,
        help="Path to coverage-manifest.json produced by gen_coverage_brief.py",
    )
    parser.add_argument(
        "--out",
        required=False,
        default=None,
        help="Path to write round-plan.md. Prints to stdout if omitted.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    try:
        manifest = load_manifest(args.manifest)
    except OSError as exc:
        print(f"ERROR: could not read manifest {args.manifest!r}: {exc}", file=sys.stderr)
        return 2
    except json.JSONDecodeError as exc:
        print(f"ERROR: manifest {args.manifest!r} is not valid JSON: {exc}", file=sys.stderr)
        return 2

    plan = render_plan(manifest, args.manifest)

    if args.out:
        Path(args.out).write_text(plan, encoding="utf-8")
        items = sandbox_must_touch(manifest)
        print(f"Wrote {args.out} ({len(items)} sandbox-tier mustTouch items)")
    else:
        print(plan)

    return 0


if __name__ == "__main__":
    sys.exit(main())
