// SPDX-License-Identifier: Apache-2.0
/**
 * <jf-failed-jobs-drawer> — Tempdoc 599 §16/B1.
 *
 * The per-folder "failed files" drill-down: a right-drawer (mirroring RetrospectivePanel /
 * AdvisoryInboxDrawer) opened from a folder row's clickable "N failed" badge. Lists the FAILED
 * indexing jobs under that watched root (the folder-scoped `/api/indexing-jobs/failed/by-prefix`
 * endpoint), each with its error and a Retry. Retry dispatches the existing user-audience Operation
 * `core.retry-indexing-job` DIRECTLY via the OperationClient (the failed-jobs Resource itself is
 * operator-only, so we do not surface it as a Resource view here — we reuse the Operation, not the
 * Resource). After a retry the list refetches; the folder row's count then drops on its own live tick.
 */
import { html, css, nothing, type TemplateResult } from 'lit';
import { JfElement } from '../primitives/JfElement.js';
import './Button.js';
import './RowActions.js';
import { icon } from './Icon.js';
import { TransientController } from '../primitives/transientController.js';
import {
  isFailedJobsOpen,
  failedJobsFolderPathHash,
  closeFailedJobs,
  subscribeFailedJobs,
} from '../state/failedJobsDrawer.js';
import { resolvePathLazy } from '../hooks/resolvePathLazy.js';
import { authorizedFetch } from '../api/authorizedFetch.js';
import { getOperationClient } from '../operations/OperationClient.js';
// Tempdoc 911 (885 UL.9) — the by-prefix wire has a contract now: the generated
// record → JSON Schema → {type, Zod} projection of `FailedIndexingJobsResponse`. `state` (the
// RETRY_EXHAUSTED discriminator below) is a declared, required field rather than a String() cast
// off untyped JSON, so a backend that renames or drops it is reported instead of silently
// rendering every row as a plain parse failure — loudly in dev (the boundary throws), as a
// console `[WireContract]` line plus a drift-telemetry entry in prod, where `toRow` below keeps
// the degrade a degrade.
import { parseWireContract } from '../../api/schemas.js';
import {
  failedIndexingJobsResponseSchema,
  type FailedIndexingJobsResponse,
} from '../../api/generated/schema-types/failed-indexing-jobs-response.js';
// Tempdoc 885 item 21b — the ONE spelling of the exhausted terminal state (see its javadoc). The
// by-prefix listing defaults a blank state to `FAILED`, so an older backend keeps the old
// rendering rather than falling into the exhausted arm.
import { JOB_STATE_RETRY_EXHAUSTED } from '../state/indexingJobStates.js';
import type { PluginHostApi } from '../plugin-api/plugin-types.js';

const RESOURCE_ID = 'core.failed-indexing-jobs';
const RETRY_OP = 'core.retry-indexing-job';

/** One row of the generated by-prefix wire contract — derived, never re-declared (564 facet 4d). */
type FailedRow = FailedIndexingJobsResponse['jobs'][number];

/**
 * Coerce the three fields this component dereferences unconditionally. In the DEV posture the
 * contract already guarantees them (the parse threw otherwise) and this is a no-op; in PROD the
 * "contract" is only a log line plus a `wireDriftTelemetry` entry, and the row is whatever the
 * drifted backend sent — so the guarantee has to be re-established here or it does not exist.
 */
function toRow(raw: FailedRow): FailedRow {
  const j = (raw ?? {}) as Partial<FailedRow>;
  return {
    ...(j as FailedRow),
    pathHash: String(j.pathHash ?? ''),
    state: String(j.state ?? ''),
    errorMessage: String(j.errorMessage ?? ''),
  };
}

export class FailedJobsDrawer extends JfElement {
  static properties = {
    open: { type: Boolean, reflect: true },
    apiBase: { attribute: 'api-base', type: String },
    host_: { attribute: false },
    rows: { state: true },
    loading: { state: true },
    error: { state: true },
    resolved: { state: true },
  };

  declare open: boolean;
  declare apiBase: string;
  declare host_: PluginHostApi | undefined;
  declare rows: FailedRow[];
  declare loading: boolean;
  declare error: string | null;
  /** pathHash → resolved display path (lazy). */
  declare resolved: Record<string, string>;

  private unsub: (() => void) | null = null;

  // 574 §23.B — single-open arbitration by construction; the panel reflects the failedJobsDrawer store.
  private readonly transient = new TransientController(this, {
    layer: 'right-drawer',
    id: 'failed-jobs',
    close: () => closeFailedJobs(),
  });

  constructor() {
    super();
    this.open = isFailedJobsOpen();
    this.apiBase = '';
    this.rows = [];
    this.loading = false;
    this.error = null;
    this.resolved = {};
  }

  override connectedCallback(): void {
    super.connectedCallback();
    this.unsub = subscribeFailedJobs(() => {
      const next = isFailedJobsOpen();
      const opening = next && !this.open;
      this.open = next;
      if (opening) void this.refresh();
      this.requestUpdate();
    });
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    this.unsub?.();
    this.unsub = null;
  }

  override updated(changed: Map<string, unknown>): void {
    if (changed.has('open')) {
      if (this.open) this.transient.open();
      else this.transient.close();
    }
  }

  private async refresh(): Promise<void> {
    const folder = failedJobsFolderPathHash();
    if (!folder) return;
    this.loading = true;
    this.error = null;
    try {
      const res = await this.doFetch(
        `/api/indexing-jobs/failed/by-prefix?pathHash=${encodeURIComponent(folder)}`,
      );
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const parsed = parseWireContract(
        failedIndexingJobsResponseSchema,
        await res.json(),
        'GET /api/indexing-jobs/failed/by-prefix',
      );
      // PROD-POSTURE DEFENCE. `parseWireContract` throws in dev but RETURNS THE RAW BODY in prod
      // (api/schemas.ts) — its own doc says it degrades "so the downstream mapper is defensive".
      // That mapper is this line: without it, a drifted row reaches render, and `r.state.toUpperCase()`
      // throws a TypeError inside Lit's `performUpdate` — OUTSIDE this try/catch, so `this.error`
      // would never be set and the drawer would freeze rather than degrade. Normalizing at the ONE
      // parse site (not at each render site) also covers `retryAll` and `onRowActionSuccess`, which
      // key on `pathHash`. Mirrors api/domains/indexing.ts's defensive `(parsed.jobs ?? [])`.
      this.rows = (Array.isArray(parsed?.jobs) ? parsed.jobs : []).map(toRow);
      // Lazy-resolve hashes → display paths (best-effort; deleted files resolve to null → show hash).
      for (const r of this.rows) {
        if (r.pathHash && !this.resolved[r.pathHash]) {
          void resolvePathLazy(RESOURCE_ID, r.pathHash, { apiBase: this.apiBase }).then((path) => {
            if (path) this.resolved = { ...this.resolved, [r.pathHash]: path };
          });
        }
      }
    } catch (err) {
      this.error = err instanceof Error ? err.message : String(err);
    } finally {
      this.loading = false;
    }
  }

  private doFetch(path: string): Promise<Response> {
    if (this.host_?.data?.fetch) return this.host_.data.fetch(path);
    return authorizedFetch((this.apiBase || '') + path);
  }

  /**
   * Per-row retry/cancel are rendered by {@code <jf-row-actions>} (tempdoc 599 §16.1 Move 1 — the
   * failed-jobs Resource now declares the retry/cancel item-operations); when one succeeds, drop that
   * row. The folder row's "N failed" count then updates on its own live tick.
   */
  private onRowActionSuccess(e: Event): void {
    const key = (e as CustomEvent<{ rowKey?: string }>).detail?.rowKey;
    if (key) this.rows = this.rows.filter((r) => r.pathHash !== key);
  }

  /** Header bulk action: invoke the existing retry Operation for each listed file, dropping each on
   * success (the "Retry all" analogue of the Advisories drawer's "Mark all read"). */
  private async retryAll(): Promise<void> {
    const client = getOperationClient(this.apiBase || '');
    for (const r of [...this.rows]) {
      try {
        await client.invoke(RETRY_OP, { args: { pathHash: r.pathHash } });
        this.rows = this.rows.filter((x) => x.pathHash !== r.pathHash);
      } catch {
        // Leave the failed row; its error stays visible. (Surfacing a toast is the message channel's job.)
      }
    }
  }

  static styles = css`
    :host(:not([open])) {
      display: none;
    }
    .panel {
      position: relative;
      height: 100%;
      width: 26rem;
      max-width: 90vw;
      background: var(--surface-1);
      border-left: 1px solid var(--border-default);
      box-shadow: -4px 0 16px rgba(0, 0, 0, 0.35);
      color: var(--text-primary);
      display: flex;
      flex-direction: column;
    }
    .head {
      flex-shrink: 0;
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 0.5rem;
      padding: 0.75rem 1rem;
      border-bottom: 1px solid var(--border-default);
    }
    .title {
      font-weight: 600;
      font-size: var(--font-size-sm);
    }
    .head-actions {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
    .body {
      flex: 1;
      overflow-y: auto;
      padding: 0.5rem 1rem;
    }
    /**
     * Tempdoc 914 D2 — the row STACKS; it is not a two-column flex row.
     *
     * The panel is 26rem wide and jf-row-actions renders one full-label button per declared
     * item-operation ("Retry indexing job", "Cancel indexing job"). Those buttons do not shrink, so
     * side-by-side they took 339px of the 373px row and squeezed .row-info to 22px — one
     * character per line, an 822px-tall row for a single path. The path IS the row's identity, so
     * it takes the full width and the actions sit under it; the same shape AdvisoryInboxDrawer
     * uses for its per-item action inside the same 26rem right-drawer slot.
     */
    .row {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      gap: 0.4rem;
      padding: 0.6rem 0;
      border-bottom: 1px solid var(--border-subtle);
    }
    .row-info {
      inline-size: 100%;
      min-inline-size: 0;
    }
    /* ActionButton's :host carries a form-control bottom margin sized for stacked form fields; in a
       list row that is dead space under the buttons. Withdrawn through its own token, not by
       overriding the component's rule. */
    .row jf-row-actions {
      --justsearch-shell-form-control-spacing: 0;
      max-inline-size: 100%;
    }
    .row-path {
      font-size: var(--font-size-sm);
      color: var(--text-primary);
      overflow-wrap: anywhere;
    }
    .row-error {
      margin-top: 0.15rem;
      font-size: var(--font-size-xs);
      color: var(--text-danger);
      overflow-wrap: anywhere;
    }
    /* Tempdoc 941 F2 — the scan that produced this failure. Secondary tone: it is provenance for
       correlating a row with a scan in Activity, not part of the failure's explanation. */
    .row-scan {
      margin-top: 0.15rem;
      font-size: var(--font-size-xs);
      color: var(--text-secondary);
      overflow-wrap: anywhere;
    }
    /* 885 item 21b — "we never managed to read it" is a WAITING outcome, not a verdict on the file,
       so it carries the secondary tone rather than the danger tone the parse-failure line uses. */
    .row-gaveup {
      margin-top: 0.15rem;
      font-size: var(--font-size-xs);
      color: var(--text-secondary);
      overflow-wrap: anywhere;
    }
    .empty,
    .loading {
      padding: 1.5rem 0;
      text-align: center;
      color: var(--text-secondary);
      font-size: var(--font-size-sm);
    }
  `;

  override render(): TemplateResult {
    if (!this.open) return html``;
    return html`
      <div class="panel" role="dialog" aria-label="Failed files">
        <div class="head">
          <span class="title">Failed files</span>
          <div class="head-actions">
            ${this.rows.length > 0
              ? html`<jf-button
                  size="sm"
                  variant="ghost"
                  label="Retry all failed files"
                  .onActivate=${() => void this.retryAll()}
                  >Retry all</jf-button
                >`
              : nothing}
            <jf-button
              size="sm"
              variant="ghost"
              label="Close"
              .onActivate=${() => closeFailedJobs()}
              >${icon({ name: 'x', size: 14 })}</jf-button
            >
          </div>
        </div>
        <div class="body" @row-action-success=${(e: Event) => this.onRowActionSuccess(e)}>
          ${this.renderBody()}
        </div>
      </div>
    `;
  }

  private renderBody(): TemplateResult {
    if (this.loading) return html`<div class="loading">Loading…</div>`;
    if (this.error) return html`<div class="empty">Couldn't load failed files: ${this.error}</div>`;
    if (this.rows.length === 0)
      return html`<div class="empty">No failed files in this folder.</div>`;
    return html`${this.rows.map((r) => this.renderRow(r))}`;
  }

  private renderRow(r: FailedRow): TemplateResult {
    const display = this.resolved[r.pathHash] ?? `[${r.pathHash.slice(0, 12)}…]`;
    // Tempdoc 885 item 21b — an exhausted job is NOT a bad file, and the two must not read alike.
    // `errorMessage` on such a row is whichever transient error happened last (an I/O error, a
    // parser timeout), which on its own reads as a verdict about the file; the header says what
    // actually happened and what makes the queue try again, so the error stays as detail rather
    // than as the explanation.
    const exhausted = r.state.toUpperCase() === JOB_STATE_RETRY_EXHAUSTED;
    // Tempdoc 941 F2 — the by-prefix wire has carried `scanId` since 911 but the drawer never
    // rendered it, so a failed row could not be tied back to the scan that produced it. `""` is the
    // contract's "no owning scan" (single-file ingest / watcher / pre-scan row), NOT an unknown —
    // so that case renders no line at all rather than an empty or invented one. `toRow` does not
    // normalize `scanId` (it coerces only the three fields dereferenced unconditionally), so the
    // prod-posture degrade can still deliver a non-string here.
    const scanId = typeof r.scanId === 'string' ? r.scanId : '';
    const scanShort = scanId.length > 8 ? `${scanId.slice(0, 8)}…` : scanId;
    // Per-row retry/cancel reuse the shared <jf-row-actions> (tempdoc 599 §16.1 Move 1 + §17.2): it
    // reads the failed-jobs Resource's itemOperations and dispatches the user-invocable Operation with
    // {pathHash: rowKey} — no hand-rolled button or direct OperationClient call.
    return html`
      <div class="row" data-state=${r.state || 'FAILED'}>
        <div class="row-info">
          <div class="row-path" title=${display}>${display}</div>
          ${exhausted
            ? html`<div class="row-gaveup" data-testid="failed-job-exhausted">
                Gave up after 7 days of retries — rescan the folder, or edit the file, to try again.
              </div>`
            : nothing}
          ${r.errorMessage ? html`<div class="row-error">${r.errorMessage}</div>` : nothing}
          ${scanId
            ? html`<div class="row-scan" data-testid="failed-job-scan" title=${scanId}>
                Scan ${scanShort}
              </div>`
            : nothing}
        </div>
        <jf-row-actions
          resource-id=${RESOURCE_ID}
          row-key=${r.pathHash}
          api-base=${this.apiBase}
        ></jf-row-actions>
      </div>
    `;
  }
}

if (typeof customElements !== 'undefined' && !customElements.get('jf-failed-jobs-drawer')) {
  customElements.define('jf-failed-jobs-drawer', FailedJobsDrawer);
}
