/* SPDX-License-Identifier: Apache-2.0 */
package io.justsearch.agent.api.registry;

import java.util.Objects;
import java.util.Optional;

/**
 * i18n-keyed presentation metadata for an entry.
 *
 * <p>Per tempdoc 429 §C.E + 421-extensibility.md §"Three layers, designed-in from day one"
 * Layer 1: the BE describes the entry's nature (label, description, optional icon hint,
 * optional category); the FE renderer maps these to widgets via its own theme conventions.
 * No FE-renderer string keys on the BE entry.
 *
 * <p>{@code labelKey} and {@code descriptionKey} resolve via the per-primitive message
 * catalog (e.g., {@code /api/messages/registry-operation/{locale}}). The
 * {@link io.justsearch.agent.api.registry.validator.RegistryShapeValidator} pipeline
 * enforces every key resolves against the loaded properties resource.
 *
 * <p>{@code iconHint} and {@code category} are optional descriptive strings (e.g.,
 * {@code "warning"}, {@code "destructive"}). The FE generic renderer interprets them
 * per its theme; missing/unrecognized values are ignored (soft-fail per LSP discipline).
 *
 * <p>Per tempdoc 429 §F.21 C1: this record carries no parallel naming for the LLM-facing
 * wire format. The {@link OperationRef} is the single identity for any invocable surface;
 * {@link OperationCatalog#toWireName(OperationRef)} projects it deterministically to a
 * wire-safe form (replace period and hyphen with underscore) at emission boundaries.
 */
public record Presentation(
    I18nKey labelKey,
    I18nKey descriptionKey,
    Optional<String> iconHint,
    Optional<String> category)
    implements PreciseWire {

  public Presentation {
    Objects.requireNonNull(labelKey, "labelKey");
    Objects.requireNonNull(descriptionKey, "descriptionKey");
    Objects.requireNonNull(iconHint, "iconHint");
    Objects.requireNonNull(category, "category");
  }

  /** Convenience: build a Presentation with no iconHint or category. */
  public static Presentation of(I18nKey labelKey, I18nKey descriptionKey) {
    return new Presentation(labelKey, descriptionKey, Optional.empty(), Optional.empty());
  }

  /**
   * Tempdoc 564 facet 4c: derive the i18n keys from the operation id by the
   * {@code ops.<id-suffix>.{label,description}} convention. The keys are thereby generated by
   * construction (the declaration fans out to the i18n leg) rather than hand-declared per op, so
   * they cannot drift from the id — which is what lets the convention gate be retired rather than
   * coexist with the duplication.
   */
  public static Presentation forId(NamespacedId id) {
    return forId(id, Optional.empty(), Optional.empty());
  }

  /** As {@link #forId(NamespacedId)} but with an explicit iconHint / category. */
  public static Presentation forId(
      NamespacedId id, Optional<String> iconHint, Optional<String> category) {
    String suffix = id.suffix();
    return new Presentation(
        new I18nKey("ops." + suffix + ".label"),
        new I18nKey("ops." + suffix + ".description"),
        iconHint,
        category);
  }
}
