/* SPDX-License-Identifier: Apache-2.0 */
/*
 * AUTO-GENERATED by scripts/codegen/gen-liveness-constants.mjs (tempdoc 575 §17 Face A).
 * Source: governance/observed-happening.v1.json (the "action-lifecycle" concept's liveness block).
 *
 * The single source of truth for the action-lifecycle liveness window, shared by the
 * worker heartbeat loop (IndexingLoop) and the reaper (KnowledgeServer). The FE display
 * freshness window is the same value, generated into liveness-constants.ts. Do NOT edit by
 * hand (the constant single-authority gate forbids a hand-authored copy); re-generate with:
 *   node scripts/codegen/gen-liveness-constants.mjs
 */
package io.justsearch.indexerworker.liveness;

/** Generated liveness window constants — see file header. */
public final class LivenessWindows {
  private LivenessWindows() {}

  /** Worker heartbeat cadence: refresh PROCESSING rows' last_updated at least this often. */
  public static final long HEARTBEAT_INTERVAL_MS = 30_000L;

  /** FE display-freshness window: a record is "live" only if beaten within this window. */
  public static final long DISPLAY_STALE_MS = 90_000L;

  /** Reaper window: a PROCESSING row older than this with no heartbeat is an orphan. */
  public static final long REAPER_STALE_MS = 300_000L;
}
