#!/usr/bin/env node
/** Regression tests for tempdoc 925's deterministic, licensed runtime projection. */

import assert from 'node:assert/strict';
import fsp from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import {
  REPO_ROOT,
  buildLegalProjection,
  checkGeneratedRuntime,
  compareGeneratedOutput,
  generateDevMcpRuntime,
} from './generate-dev-mcp-runtime.mjs';

process.exitCode = 1;
let passed = 0;
async function check(label, fn) {
  await fn();
  passed += 1;
  console.log(`  PASS  ${label}`);
}

const temporaryRoot = await fsp.mkdtemp(path.join(os.tmpdir(), 'justsearch-dev-runtime-test-'));
const temporaryEntryDir = path.join(REPO_ROOT, 'tmp', `dev-mcp-runtime-test-${process.pid}`);
try {
  const first = await generateDevMcpRuntime();
  const second = await generateDevMcpRuntime();

  await check('two generations are byte-identical', async () => {
    assert.equal(Buffer.compare(first.bundle, second.bundle), 0);
    assert.equal(Buffer.compare(first.legal, second.legal), 0);
    assert.equal(first.sha256, second.sha256);
  });
  await check('the committed bundle and legal projection are current', async () => {
    const result = await checkGeneratedRuntime({ generated: first });
    assert.equal(result.ok, true, result.errors.join('\n'));
  });
  await check('the runtime leaves only explicit node: built-ins external', async () => {
    assert.deepEqual(first.externalImports, ['node:process']);
  });
  await check('the runtime contains no checkout-specific absolute path', async () => {
    assert.equal(first.bundle.toString('utf8').includes(REPO_ROOT), false);
  });
  await check('the legal projection covers the exact bundled package closure', async () => {
    assert.deepEqual(first.packages.map((pkg) => pkg.name), [
      '@modelcontextprotocol/sdk',
      'ajv',
      'ajv-formats',
      'fast-deep-equal',
      'fast-uri',
      'json-schema-traverse',
      'zod',
      'zod-to-json-schema',
    ]);
  });
  await check('bundle drift is detected', async () => {
    const tampered = Buffer.concat([first.bundle, Buffer.from('\n// tampered\n')]);
    assert.match(
      compareGeneratedOutput({ expected: first.bundle, actual: tampered, label: 'runtime.generated.mjs' }),
      /is stale/,
    );
  });
  await check('legal drift is detected', async () => {
    assert.match(
      compareGeneratedOutput({ expected: first.legal, actual: Buffer.from('wrong'), label: 'runtime.generated.LEGAL.txt' }),
      /is stale/,
    );
  });

  await fsp.mkdir(temporaryEntryDir, { recursive: true });
  const relativeEntry = path.relative(REPO_ROOT, path.join(temporaryEntryDir, 'runtime-entry.mjs')).replace(/\\/g, '/');
  await fsp.writeFile(
    path.join(REPO_ROOT, relativeEntry),
    [
      "export { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';",
      "export { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';",
      "export * as z from 'zod/v4';",
      'export const deliberatelyChangedInput = true;',
      '',
    ].join('\n'),
    'utf8',
  );
  await check('a behavior-bearing entry change alters the generated bytes', async () => {
    const changed = await generateDevMcpRuntime({ entryRel: relativeEntry });
    assert.notEqual(Buffer.compare(first.bundle, changed.bundle), 0);
  });
  await fsp.writeFile(
    path.join(REPO_ROOT, relativeEntry),
    "export { readFile } from 'fs';\n",
    'utf8',
  );
  await check('a non-node-prefixed external import fails closed', async () => {
    await assert.rejects(
      () => generateDevMcpRuntime({ entryRel: relativeEntry }),
      /non-builtin external import\(s\): fs/,
    );
  });

  const badPackageRoot = path.join(temporaryRoot, 'node_modules', 'bad-license');
  await fsp.mkdir(badPackageRoot, { recursive: true });
  await fsp.writeFile(
    path.join(badPackageRoot, 'package.json'),
    JSON.stringify({ name: 'bad-license', version: '1.0.0', license: 'Proprietary' }),
    'utf8',
  );
  const badMetafile = { inputs: { 'node_modules/bad-license/index.js': {} } };
  await check('an unapproved package license fails closed', async () => {
    assert.throws(
      () => buildLegalProjection({ metafile: badMetafile, repoRoot: temporaryRoot }),
      /unsupported license/,
    );
  });

  await fsp.writeFile(
    path.join(badPackageRoot, 'package.json'),
    JSON.stringify({ name: 'bad-license', version: '1.0.0', license: 'MIT' }),
    'utf8',
  );
  await check('a package without license text fails closed', async () => {
    assert.throws(
      () => buildLegalProjection({ metafile: badMetafile, repoRoot: temporaryRoot }),
      /no LICENSE\/COPYING\/NOTICE file/,
    );
  });

  console.log(`generate-dev-mcp-runtime.test: ${passed} passed`);
  process.exitCode = 0;
} finally {
  await fsp.rm(temporaryRoot, { recursive: true, force: true });
  await fsp.rm(temporaryEntryDir, { recursive: true, force: true });
}
