#!/usr/bin/env node
/**
 * Tempdoc 632 — attribution-as-projection.
 *
 * Single authority for "what JustSearch redistributes and under what license" is a set of
 * declarations (the jk1 dependency report, the npm license dump, model-registry.v2.json, and the
 * native-binary manifests). This generator PROJECTS them into the committed `NOTICE` +
 * `THIRD_PARTY_NOTICES`; it is never hand-edited. `--check` re-projects and fails on drift (the
 * closure/equality half, conforming to the repo's gen-*.mjs / check-*-regen pattern), plus a set of
 * presence checks (every model has a license; the two registry copies match; every bundled Tesseract
 * DLL is attributed). Run after `generateLicenseReport` + `license-checker` have produced their dumps.
 *
 * Usage:  node scripts/codegen/gen-notices.mjs [--check]
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');

// --- Inputs (declarations) ---------------------------------------------------
const JK1_REPORT = join(REPO_ROOT, 'build', 'reports', 'licenses', 'third-party-licenses.json');
const NPM_DUMP = join(REPO_ROOT, 'build', 'npm-licenses.json');
const CARGO_DUMP = join(REPO_ROOT, 'build', 'cargo-licenses.json');
const REGISTRY_PROD = join(REPO_ROOT, 'modules', 'ui', 'src', 'main', 'resources', 'ai', 'model-registry.v2.json');
const REGISTRY_TEST = join(REPO_ROOT, 'modules', 'configuration', 'src', 'test', 'resources', 'ai', 'model-registry.v2.json');
const TESS_CORE = join(REPO_ROOT, 'packaging', 'runtime', 'tesseract-windows.v1.json');
const TESS_DLLS = join(REPO_ROOT, 'packaging', 'runtime', 'tesseract-bundled-libraries.v1.json');
const OVERRIDES = join(REPO_ROOT, 'scripts', 'codegen', 'license-overrides.json');
const ALLOWED_LICENSES = join(REPO_ROOT, 'config', 'allowed-licenses.json');
const NATIVE_ACCEPTANCES = join(REPO_ROOT, 'config', 'native-license-acceptances.json');
const NATIVE_BIN_TESS = join(REPO_ROOT, 'native-bin', 'tesseract'); // gitignored; present only where staged

// --- Outputs (projections) ---------------------------------------------------
const NOTICE_OUT = join(REPO_ROOT, 'NOTICE');
const TPN_OUT = join(REPO_ROOT, 'THIRD_PARTY_NOTICES');
// Installer-bundled model attribution — the Gradle `generateOnnxNotice` task copies this committed,
// registry-projected file into the bundle instead of hardcoding a heredoc (tempdoc 632).
const NOTICE_MODELS_OUT = join(REPO_ROOT, 'packaging', 'runtime', 'NOTICE-MODELS.txt');
// Canonical legal doc — the model/license TABLE is a generated region (tempdoc 632), projected from the
// registry into a marked span so it can't drift (the same closure as the notices).
const LEGAL_DOC = join(REPO_ROOT, 'docs', 'reference', 'legal', 'ai-runtime-and-model-redistribution.md');
const LEGAL_MARK_START = '<!-- GENERATED:MODEL_LICENSES:BEGIN — do not edit; run: node scripts/codegen/gen-notices.mjs -->';
const LEGAL_MARK_END = '<!-- GENERATED:MODEL_LICENSES:END -->';

const GEN_BANNER =
  'AUTO-GENERATED by scripts/codegen/gen-notices.mjs — do NOT edit by hand.\n' +
  'Regenerate: node scripts/codegen/gen-notices.mjs (after `gradlew generateLicenseReport` + `license-checker`).';

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

/** JVM deps from the jk1 report, with dual-licensed deps claimed under their permissive override. */
function loadJvm(report = readJson(JK1_REPORT), overrides = readJson(OVERRIDES)) {
  const ov = overrides.jvmModuleLicense || {};
  const seen = new Map();
  for (const d of report.dependencies || []) {
    const license = ov[d.moduleName] || d.moduleLicense || 'UNKNOWN';
    const key = `${d.moduleName}@${d.moduleVersion}`;
    seen.set(key, { name: d.moduleName, version: d.moduleVersion || '', license });
  }
  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

/** Frontend npm deps from the license-checker dump (key = name@version). */
function loadNpm(dump = readJson(NPM_DUMP)) {
  return Object.entries(dump)
    .map(([k, v]) => {
      const at = k.lastIndexOf('@');
      return {
        name: k.slice(0, at),
        version: k.slice(at + 1),
        license: Array.isArray(v.licenses) ? v.licenses.join(' OR ') : String(v.licenses || 'UNKNOWN'),
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

/** Rust/Cargo deps of the Tauri desktop shell (statically linked → redistributed). */
function loadCargo(dump = readJson(CARGO_DUMP)) {
  return [...dump].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
}

/** Bundled ML models — the registry is the SSOT for their licenses. */
function loadModels(registry = readJson(REGISTRY_PROD)) {
  return (registry.packages || [])
    .map((p) => ({ id: p.id, label: p.label, license: p.license, termsUrl: p.termsUrl, targetDir: p.targetDir }))
    .sort((a, b) => a.id.localeCompare(b.id));
}

function loadNative(overrides = readJson(OVERRIDES), tessCore = readJson(TESS_CORE), tessDlls = readJson(TESS_DLLS)) {
  return { runtimes: overrides.nativeRuntimes || [], tessCore, tessDlls };
}

// --- Rendering ---------------------------------------------------------------
function renderThirdParty(jvm, npm, models, native, cargo = []) {
  const L = [];
  L.push('JustSearch — Third-Party Notices');
  L.push('================================');
  L.push('');
  L.push(GEN_BANNER);
  L.push('');
  L.push('Licenses of third-party components redistributed with JustSearch.');
  L.push('');
  L.push('== Java / JVM dependencies ==');
  for (const d of jvm) L.push(`  ${d.name} ${d.version} — ${d.license}`);
  L.push('');
  L.push('== Frontend (npm) dependencies ==');
  for (const d of npm) L.push(`  ${d.name} ${d.version} — ${d.license}`);
  L.push('');
  L.push('== Rust / Cargo (desktop shell) dependencies ==');
  for (const d of cargo) L.push(`  ${d.name} ${d.version} — ${d.license}`);
  L.push('');
  L.push('== Bundled ML models ==');
  for (const m of models) L.push(`  ${m.label} (${m.id}) — ${m.license} — ${m.termsUrl}`);
  L.push('');
  L.push('== Native runtime binaries ==');
  for (const r of native.runtimes) {
    L.push(`  ${r.name} — ${r.license}`);
    L.push(`    ${r.ref}${r.bundled ? `; bundled: ${r.bundled}` : ''}`);
  }
  L.push('');
  L.push(`  Tesseract OCR ${native.tessCore.version} — ${native.tessCore.license}; English tessdata — Apache-2.0`);
  L.push('  Bundled Windows runtime libraries (MSYS2/mingw-w64):');
  // Group DLL entries by library to keep the notice compact + deterministic.
  const byLib = new Map();
  for (const e of [...native.tessDlls.libraries].sort((a, b) => a.library.localeCompare(b.library))) {
    if (!byLib.has(e.library)) byLib.set(e.library, e.license);
  }
  for (const [lib, lic] of byLib) L.push(`    ${lib} — ${lic}`);
  L.push('');
  return L.join('\n') + '\n';
}

/** Installer-bundled model attribution, projected from the registry (replaces the old heredoc). */
function renderModelsNotice(models) {
  const L = [];
  L.push('Bundled Search & Chat Models');
  L.push('============================');
  L.push('');
  L.push(GEN_BANNER);
  L.push('');
  L.push('Pre-trained models bundled for indexing, retrieval, reranking, entity');
  L.push('recognition, citation scoring, and chat. Each is redistributed under the');
  L.push('license below (single-sourced from ai/model-registry.v2.json).');
  L.push('');
  for (const m of models.filter((x) => x.id !== 'cuda-runtime')) {
    L.push(`${m.label} (${m.id})`);
    if (m.targetDir) L.push(`  path: ${m.targetDir}`);
    L.push(`  license: ${m.license}`);
    if (m.termsUrl) L.push(`  terms: ${m.termsUrl}`);
    L.push('');
  }
  return L.join('\n');
}

/** The canonical-doc model/license table, projected from the registry (Model | License | Source). */
function renderModelLicenseTable(models) {
  const rows = models
    .filter((m) => m.id !== 'cuda-runtime')
    .map((m) => {
      const src = m.termsUrl ? `[${m.termsUrl.replace(/^https?:\/\//, '')}](${m.termsUrl})` : '—';
      return `| ${m.label} (\`${m.id}\`) | ${m.license} | ${src} |`;
    });
  return ['| Model | License | Source |', '|-------|---------|--------|', ...rows].join('\n');
}

/** Splice the generated model-license table into the legal doc's marked region (llmstxt-style). */
function injectLegalDocTable(models, existing = readFileSync(LEGAL_DOC, 'utf8')) {
  const s = existing.indexOf(LEGAL_MARK_START);
  const e = existing.indexOf(LEGAL_MARK_END);
  if (s === -1 || e === -1) {
    throw new Error(`${LEGAL_DOC} is missing the MODEL_LICENSES markers — add them, then re-run gen-notices`);
  }
  const before = existing.slice(0, s);
  const after = existing.slice(e + LEGAL_MARK_END.length);
  return `${before}${LEGAL_MARK_START}\n${renderModelLicenseTable(models)}\n${LEGAL_MARK_END}${after}`;
}

function renderNotice(models) {
  const modelLine = models
    .filter((m) => m.id !== 'cuda-runtime')
    .map((m) => `${m.id} (${m.license})`)
    .join(', ');
  return (
    'JustSearch\n' +
    'Copyright 2025 JustSearch Contributors\n' +
    '\n' +
    'This product includes software developed by the Apache Software Foundation\n' +
    '(https://www.apache.org/).\n' +
    '\n' +
    'Licensed under the Apache License, Version 2.0 — see the LICENSE file.\n' +
    '\n' +
    'This product redistributes third-party components; the complete, generated\n' +
    'attribution list is in THIRD_PARTY_NOTICES. Principal components:\n' +
    '\n' +
    '  Apache Lucene — Apache-2.0\n' +
    '  Apache Tika — Apache-2.0\n' +
    '  ONNX Runtime — MIT\n' +
    '  Javalin — Apache-2.0; Eclipse Jetty — EPL-2.0; Deep Java Library (DJL) — Apache-2.0\n' +
    '  llama.cpp — MIT\n' +
    '  Tauri + Rust crates (desktop shell) — Apache-2.0 / MIT (full list in THIRD_PARTY_NOTICES)\n' +
    `  Bundled ML models: ${modelLine}\n` +
    '  Tesseract OCR + bundled MSYS2/mingw-w64 libraries — see THIRD_PARTY_NOTICES\n' +
    '  NVIDIA CUDA runtime (CUDA Toolkit EULA) and cuDNN (cuDNN SLA) — GPU builds only\n'
  );
}

/**
 * True if `license` is strong copyleft (GPL/AGPL/SSPL) with NO permissive alternative and NO linking
 * exception — i.e. the one class that needs review before redistribution in a permissive bundle.
 * LGPL/MPL/EPL (weak/file-level, fine as separate components) and GPL-WITH-exception (GCC runtime) and
 * any dual that offers a permissive option are NOT flagged.
 */
function isStrongCopyleft(license) {
  if (!license || license === 'UNKNOWN') return false; // UNKNOWN is a separate check
  const strongCopyleft = /\b(?:A?GPL|SSPL)\b/i; // \bGPL does NOT match "LGPL" (no word boundary before G)
  const exceptionOk = /WITH .*exception/i;
  const permissiveAlt = /\b(?:MIT|BSD|Apache|MPL|ISC|Zlib|0BSD|Unicode|CC0|Unlicense)\b/i;
  return strongCopyleft.test(license) && !exceptionOk.test(license) && !permissiveAlt.test(license);
}

// The 5 native-binary dispositions. FIRING ones require a dated acceptance (tempdoc 632 disposition gate).
const NATIVE_DISPOSITIONS = new Set([
  'permissive',
  'weak-copyleft-dynamic', // LGPL/MPL as a separate replaceable DLL — ship the text, no waiver needed
  'copyleft-with-linking-exception', // GCC runtime — exception permits non-GPL linking; ship the exception text
  'strong-copyleft', // GPL/AGPL with no permissive alternative — FIRING
  'restricted', // EULA/SLA/field-of-use — FIRING
]);
const FIRING_DISPOSITIONS = new Set(['strong-copyleft', 'restricted']);

/**
 * The native-binary policy gate (tempdoc 632). The dependency-tree analogue is jk1 `checkLicense` over
 * config/allowed-licenses.json; this is the native equivalent over the committed manifests (so it runs in CI
 * without native-bin staged). Disposition is an EXPLICIT declared field — never regex-derived (FreeType
 * FTL-OR-GPL, GCC WITH-exception, libidn2 LGPL-OR-GPL all defeat naive classification). Three assertions:
 *   (1) no silent default — every native artifact carries a valid disposition;
 *   (2) firing requires acceptance — strong-copyleft|restricted needs a dated entry in the acceptance ledger;
 *   (3) no stale acceptance — every acceptance maps to a currently-firing artifact (a waiver can't outlive it).
 * Pure + injectable (mirrors the loaders) so the test drives it with crafted data.
 */
function nativeDispositionCheck(native = loadNative(), ledger = readJson(NATIVE_ACCEPTANCES)) {
  const errors = [];
  const accepted = new Set((ledger.acceptances || []).map((a) => a.artifact));
  // Redistributed third-party native surface = the Tesseract bundled DLLs + the nativeRuntimes block.
  // tessCore (the Tesseract engine pin) is Apache-2.0 and already covered by its libtesseract-5.dll row.
  const artifacts = [
    ...native.tessDlls.libraries.map((l) => ({ name: l.library, disposition: l.disposition })),
    ...(native.runtimes || []).map((r) => ({ name: r.name, disposition: r.disposition })),
  ];
  const firingNames = new Set();
  for (const a of artifacts) {
    if (!a.disposition || !NATIVE_DISPOSITIONS.has(a.disposition)) {
      errors.push(`native artifact '${a.name}' has missing/invalid disposition '${a.disposition}' — classify it in the manifest (one of: ${[...NATIVE_DISPOSITIONS].join(', ')})`);
      continue;
    }
    if (FIRING_DISPOSITIONS.has(a.disposition)) {
      firingNames.add(a.name);
      if (!accepted.has(a.name)) {
        errors.push(`native artifact '${a.name}' is ${a.disposition} (FIRING) with NO dated acceptance — add an entry to config/native-license-acceptances.json or remove the artifact`);
      }
    }
  }
  // (3) symmetric: no acceptance may outlive its firing artifact.
  for (const artifact of accepted) {
    if (!firingNames.has(artifact)) {
      errors.push(`acceptance for '${artifact}' has no matching firing native artifact — remove the stale entry from config/native-license-acceptances.json`);
    }
  }
  return errors;
}

// --- Presence checks (the closure half) --------------------------------------
function presenceChecks() {
  const errors = [];
  // 1. every model package declares a license
  const reg = readJson(REGISTRY_PROD);
  for (const p of reg.packages || []) {
    if (!p.license || !String(p.license).trim()) errors.push(`model package '${p.id}' has no license (632 SSOT)`);
  }
  // 2. the two registry copies are byte-identical (currently ungated dual-copy)
  if (readFileSync(REGISTRY_PROD, 'utf8') !== readFileSync(REGISTRY_TEST, 'utf8')) {
    errors.push('model-registry prod and test copies differ — keep them byte-identical');
  }
  // 2b. the gate allowlist's per-moduleName allows must match the NOTICE overrides' moduleNames
  //     (the dual-licensed / junrar / jcip special-cases live in BOTH files; this keeps them from drifting
  //     apart — the design's "no silent fork", as a check rather than full generation since the allowlist's
  //     permissive-license strings have a different change-reason and stay hand-authored).
  if (existsSync(ALLOWED_LICENSES) && existsSync(OVERRIDES)) {
    const allowNames = new Set(
      (readJson(ALLOWED_LICENSES).allowedLicenses || []).filter((e) => e.moduleName).map((e) => e.moduleName),
    );
    const overrideNames = new Set(Object.keys(readJson(OVERRIDES).jvmModuleLicense || {}));
    for (const n of overrideNames) {
      if (!allowNames.has(n)) errors.push(`'${n}' is in license-overrides.json but NOT allowlisted in config/allowed-licenses.json`);
    }
    for (const n of allowNames) {
      if (!overrideNames.has(n)) errors.push(`'${n}' is allowlisted by moduleName but has NO NOTICE override in license-overrides.json`);
    }
  }
  // 3. every bundled Tesseract DLL is attributed (skip-when-absent: native-bin is gitignored / installer-staged)
  if (existsSync(NATIVE_BIN_TESS)) {
    const table = new Set(readJson(TESS_DLLS).libraries.map((l) => l.dll));
    const actual = readdirSync(NATIVE_BIN_TESS).filter((f) => f.endsWith('.dll'));
    for (const dll of actual) {
      if (!table.has(dll)) errors.push(`Tesseract DLL '${dll}' is not attributed in tesseract-bundled-libraries.v1.json`);
    }
  }
  // 4. no UNKNOWN license slipped into the attribution, and no strong copyleft in any shipped tree.
  //    The jk1 gate only covers the JVM classpath, so this is the only copyleft guard on the npm + Cargo trees.
  //    Strong copyleft = GPL/AGPL/SSPL (not LGPL/MPL/EPL, which are fine as separate/dynamic components). A bare
  //    "GPL-...-WITH-...-exception" (e.g. the GCC runtime) is permitted; the native Tesseract table owns those.
  if (existsSync(JK1_REPORT) && existsSync(NPM_DUMP) && existsSync(CARGO_DUMP)) {
    for (const d of [...loadJvm(), ...loadNpm(), ...loadCargo()]) {
      if (d.license === 'UNKNOWN') {
        errors.push(`${d.name} ${d.version} has an UNKNOWN license — add an override in license-overrides.json`);
      } else if (isStrongCopyleft(d.license)) {
        errors.push(`${d.name} ${d.version} is strong copyleft with no permissive alternative (${d.license}) — review before redistribution`);
      }
    }
  }
  // 5. native-binary disposition gate — the policy half for the native axis (the jk1 gate covers only the JVM
  //    classpath; checks 1-4 cover presence/equality but not native redistribution POLICY). Closes the proven
  //    libjbig silent-GPL-ship blind spot: a FIRING native disposition (strong-copyleft/restricted) needs a dated
  //    acceptance, mirroring checkLicense's allowlist. Runs on the committed manifests → unconditional in CI.
  errors.push(...nativeDispositionCheck());
  return errors;
}

function build() {
  const jvm = loadJvm();
  const npm = loadNpm();
  const models = loadModels();
  const native = loadNative();
  const cargo = loadCargo();
  return [
    { path: NOTICE_OUT, content: renderNotice(models) },
    { path: TPN_OUT, content: renderThirdParty(jvm, npm, models, native, cargo) },
    { path: NOTICE_MODELS_OUT, content: renderModelsNotice(models) },
    { path: LEGAL_DOC, content: injectLegalDocTable(models) },
  ];
}

function main() {
  const check = process.argv.includes('--check');

  const presence = presenceChecks();
  if (presence.length) {
    console.error('NOTICE presence checks FAILED:');
    for (const e of presence) console.error(`  - ${e}`);
    process.exit(1);
  }

  const outputs = build();
  if (check) {
    const drift = [];
    for (const { path, content } of outputs) {
      const before = existsSync(path) ? readFileSync(path, 'utf8') : null;
      if (before !== content) drift.push(path);
    }
    if (drift.length) {
      console.error('NOTICE projection is STALE — these files drifted from their sources:');
      for (const p of drift) console.error(`  - ${p}`);
      console.error('Regenerate: node scripts/codegen/gen-notices.mjs');
      process.exit(1);
    }
    console.log('gen-notices --check: NOTICE + THIRD_PARTY_NOTICES are in sync.');
    return;
  }

  for (const { path, content } of outputs) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, 'utf8');
    console.log(`wrote ${path}`);
  }
}

const isMain = import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  try {
    main();
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}

export {
  loadJvm, loadNpm, loadModels, loadNative, loadCargo,
  renderNotice, renderThirdParty, renderModelsNotice, renderModelLicenseTable, injectLegalDocTable,
  presenceChecks, isStrongCopyleft, nativeDispositionCheck,
  NOTICE_OUT, TPN_OUT, NOTICE_MODELS_OUT,
};
