/**
 * AUTO-GENERATED by scripts/ci/gen-token-names.mjs — DO NOT EDIT.
 *
 * The closed design-token vocabulary (tempdoc 557 §2.C). Regenerate with
 * `node scripts/ci/gen-token-names.mjs` after adding a token to tokens.css.
 * The `token()` accessor (themes/token.ts) is typed against this union, so a
 * misspelled token name is a compile error — not a silent ghost fallback.
 */

export type TokenName =
  | '--accent'
  | '--accent-chat'
  | '--accent-chat-08'
  | '--accent-chat-16'
  | '--accent-chat-30'
  | '--accent-chat-45'
  | '--accent-command'
  | '--accent-command-08'
  | '--accent-command-16'
  | '--accent-command-30'
  | '--accent-command-45'
  | '--accent-danger'
  | '--accent-danger-08'
  | '--accent-danger-16'
  | '--accent-danger-30'
  | '--accent-danger-45'
  | '--accent-danger-weak'
  | '--accent-highlight'
  | '--accent-info'
  | '--accent-link'
  | '--accent-on-chat'
  | '--accent-on-command'
  | '--accent-on-danger'
  | '--accent-on-highlight'
  | '--accent-on-link'
  | '--accent-on-success'
  | '--accent-on-tint'
  | '--accent-on-warning'
  | '--accent-primary'
  | '--accent-primary-weak'
  | '--accent-purple'
  | '--accent-success'
  | '--accent-success-08'
  | '--accent-success-16'
  | '--accent-success-30'
  | '--accent-success-45'
  | '--accent-success-hover'
  | '--accent-tint'
  | '--accent-tint-08'
  | '--accent-tint-16'
  | '--accent-tint-30'
  | '--accent-tint-45'
  | '--accent-tint-hover'
  | '--accent-tint-weak'
  | '--accent-warm'
  | '--accent-warm-muted'
  | '--accent-warning'
  | '--accent-warning-08'
  | '--accent-warning-16'
  | '--accent-warning-30'
  | '--accent-warning-45'
  | '--accent-warning-weak'
  | '--border-default'
  | '--border-emphasized'
  | '--border-muted'
  | '--border-strong'
  | '--border-subtle'
  | '--cat-code'
  | '--cat-doc'
  | '--cat-folder'
  | '--cat-image'
  | '--cat-note'
  | '--cat-pdf'
  | '--code-bg-block'
  | '--code-bg-inline'
  | '--color-accent'
  | '--color-accent-chat'
  | '--color-accent-command'
  | '--color-accent-danger'
  | '--color-accent-success'
  | '--color-accent-warm'
  | '--color-accent-warm-muted'
  | '--color-accent-warning'
  | '--color-glass-border'
  | '--color-glass-border-hover'
  | '--color-glass-border-strong'
  | '--color-glass-surface'
  | '--color-glass-surface-active'
  | '--color-glass-surface-hover'
  | '--color-layer-base'
  | '--color-layer-base-solid'
  | '--color-surface-0'
  | '--color-surface-1'
  | '--color-surface-2'
  | '--color-surface-3'
  | '--color-surface-4'
  | '--color-text-ghost'
  | '--color-text-muted'
  | '--color-text-primary'
  | '--color-text-secondary'
  | '--color-text-tertiary'
  | '--command-height'
  | '--danger-tint'
  | '--density-header-pad-x'
  | '--density-header-pad-y'
  | '--density-inner-pad-x'
  | '--density-inner-pad-y'
  | '--density-pad-x'
  | '--density-pad-y'
  | '--density-panel-pad-x'
  | '--density-panel-pad-y'
  | '--density-stack-gap'
  | '--density-stack-gap-lg'
  | '--density-stack-gap-sm'
  | '--duration-fast'
  | '--duration-instant'
  | '--duration-normal'
  | '--duration-slow'
  | '--ease-accelerate'
  | '--ease-decelerate'
  | '--ease-standard'
  | '--error-bg'
  | '--error-border'
  | '--focus-ring-color'
  | '--font-display'
  | '--font-mono'
  | '--font-native'
  | '--font-size-lg'
  | '--font-size-md'
  | '--font-size-sm'
  | '--font-size-xl'
  | '--font-size-xs'
  | '--glass-blur'
  | '--glass-blur-elevated'
  | '--glass-border'
  | '--glass-border-hover'
  | '--glass-border-strong'
  | '--glass-saturation'
  | '--glass-saturation-elevated'
  | '--glass-surface'
  | '--glass-surface-active'
  | '--glass-surface-hover'
  | '--glow-accent'
  | '--glow-danger'
  | '--glow-focus'
  | '--glow-hover-subtle'
  | '--glow-inset-rim'
  | '--glow-inset-subtle'
  | '--glow-success'
  | '--glow-warm'
  | '--glow-warning'
  | '--gutter-icon'
  | '--h-amber'
  | '--h-blue'
  | '--h-green'
  | '--h-magenta'
  | '--h-purple'
  | '--h-red'
  | '--h-teal'
  | '--halo-shadow'
  | '--inspector-width-collapsed'
  | '--inspector-width-expanded'
  | '--jf-font-mono'
  | '--justsearch-shell-form-label-color'
  | '--justsearch-shell-text'
  | '--layer-base'
  | '--layer-base-solid'
  | '--p-glass'
  | '--p-shadow'
  | '--p-text'
  | '--rail-icon-hover'
  | '--rail-icon-inactive'
  | '--rail-width'
  | '--result-row-cursor'
  | '--result-row-hover'
  | '--scrollbar-thumb'
  | '--scrollbar-thumb-hover'
  | '--scrollbar-track'
  | '--selection-bg'
  | '--shadow-card'
  | '--shadow-card-sm'
  | '--shadow-float'
  | '--shadow-glass'
  | '--shadow-glass-panel'
  | '--shadow-lift'
  | '--shadow-menu'
  | '--shadow-panel-edge'
  | '--status-height'
  | '--success-tint'
  | '--surface-0'
  | '--surface-1'
  | '--surface-2'
  | '--surface-3'
  | '--surface-4'
  | '--surface-active'
  | '--surface-content-max-width'
  | '--surface-hover'
  | '--surface-primary'
  | '--surface-secondary'
  | '--surface-subtle'
  | '--surface-tertiary'
  | '--text-chat'
  | '--text-command'
  | '--text-danger'
  | '--text-ghost'
  | '--text-highlight'
  | '--text-link'
  | '--text-muted'
  | '--text-primary'
  | '--text-secondary'
  | '--text-success'
  | '--text-tertiary'
  | '--text-tint'
  | '--text-warning'
  | '--toggle-track-off'
  | '--tooltip-bg'
  | '--tooltip-shadow'
  | '--warning-tint'
  | '--z-base'
  | '--z-float'
  | '--z-glass'
  | '--z-modal'
  | '--z-overlay-chrome'
  | '--z-overlay-drawer'
  | '--z-overlay-float'
  | '--z-overlay-modal'
  | '--z-overlay-top'
  | '--z-overlay-transient';

export const TOKEN_NAMES: readonly TokenName[] = [
  '--accent',
  '--accent-chat',
  '--accent-chat-08',
  '--accent-chat-16',
  '--accent-chat-30',
  '--accent-chat-45',
  '--accent-command',
  '--accent-command-08',
  '--accent-command-16',
  '--accent-command-30',
  '--accent-command-45',
  '--accent-danger',
  '--accent-danger-08',
  '--accent-danger-16',
  '--accent-danger-30',
  '--accent-danger-45',
  '--accent-danger-weak',
  '--accent-highlight',
  '--accent-info',
  '--accent-link',
  '--accent-on-chat',
  '--accent-on-command',
  '--accent-on-danger',
  '--accent-on-highlight',
  '--accent-on-link',
  '--accent-on-success',
  '--accent-on-tint',
  '--accent-on-warning',
  '--accent-primary',
  '--accent-primary-weak',
  '--accent-purple',
  '--accent-success',
  '--accent-success-08',
  '--accent-success-16',
  '--accent-success-30',
  '--accent-success-45',
  '--accent-success-hover',
  '--accent-tint',
  '--accent-tint-08',
  '--accent-tint-16',
  '--accent-tint-30',
  '--accent-tint-45',
  '--accent-tint-hover',
  '--accent-tint-weak',
  '--accent-warm',
  '--accent-warm-muted',
  '--accent-warning',
  '--accent-warning-08',
  '--accent-warning-16',
  '--accent-warning-30',
  '--accent-warning-45',
  '--accent-warning-weak',
  '--border-default',
  '--border-emphasized',
  '--border-muted',
  '--border-strong',
  '--border-subtle',
  '--cat-code',
  '--cat-doc',
  '--cat-folder',
  '--cat-image',
  '--cat-note',
  '--cat-pdf',
  '--code-bg-block',
  '--code-bg-inline',
  '--color-accent',
  '--color-accent-chat',
  '--color-accent-command',
  '--color-accent-danger',
  '--color-accent-success',
  '--color-accent-warm',
  '--color-accent-warm-muted',
  '--color-accent-warning',
  '--color-glass-border',
  '--color-glass-border-hover',
  '--color-glass-border-strong',
  '--color-glass-surface',
  '--color-glass-surface-active',
  '--color-glass-surface-hover',
  '--color-layer-base',
  '--color-layer-base-solid',
  '--color-surface-0',
  '--color-surface-1',
  '--color-surface-2',
  '--color-surface-3',
  '--color-surface-4',
  '--color-text-ghost',
  '--color-text-muted',
  '--color-text-primary',
  '--color-text-secondary',
  '--color-text-tertiary',
  '--command-height',
  '--danger-tint',
  '--density-header-pad-x',
  '--density-header-pad-y',
  '--density-inner-pad-x',
  '--density-inner-pad-y',
  '--density-pad-x',
  '--density-pad-y',
  '--density-panel-pad-x',
  '--density-panel-pad-y',
  '--density-stack-gap',
  '--density-stack-gap-lg',
  '--density-stack-gap-sm',
  '--duration-fast',
  '--duration-instant',
  '--duration-normal',
  '--duration-slow',
  '--ease-accelerate',
  '--ease-decelerate',
  '--ease-standard',
  '--error-bg',
  '--error-border',
  '--focus-ring-color',
  '--font-display',
  '--font-mono',
  '--font-native',
  '--font-size-lg',
  '--font-size-md',
  '--font-size-sm',
  '--font-size-xl',
  '--font-size-xs',
  '--glass-blur',
  '--glass-blur-elevated',
  '--glass-border',
  '--glass-border-hover',
  '--glass-border-strong',
  '--glass-saturation',
  '--glass-saturation-elevated',
  '--glass-surface',
  '--glass-surface-active',
  '--glass-surface-hover',
  '--glow-accent',
  '--glow-danger',
  '--glow-focus',
  '--glow-hover-subtle',
  '--glow-inset-rim',
  '--glow-inset-subtle',
  '--glow-success',
  '--glow-warm',
  '--glow-warning',
  '--gutter-icon',
  '--h-amber',
  '--h-blue',
  '--h-green',
  '--h-magenta',
  '--h-purple',
  '--h-red',
  '--h-teal',
  '--halo-shadow',
  '--inspector-width-collapsed',
  '--inspector-width-expanded',
  '--jf-font-mono',
  '--justsearch-shell-form-label-color',
  '--justsearch-shell-text',
  '--layer-base',
  '--layer-base-solid',
  '--p-glass',
  '--p-shadow',
  '--p-text',
  '--rail-icon-hover',
  '--rail-icon-inactive',
  '--rail-width',
  '--result-row-cursor',
  '--result-row-hover',
  '--scrollbar-thumb',
  '--scrollbar-thumb-hover',
  '--scrollbar-track',
  '--selection-bg',
  '--shadow-card',
  '--shadow-card-sm',
  '--shadow-float',
  '--shadow-glass',
  '--shadow-glass-panel',
  '--shadow-lift',
  '--shadow-menu',
  '--shadow-panel-edge',
  '--status-height',
  '--success-tint',
  '--surface-0',
  '--surface-1',
  '--surface-2',
  '--surface-3',
  '--surface-4',
  '--surface-active',
  '--surface-content-max-width',
  '--surface-hover',
  '--surface-primary',
  '--surface-secondary',
  '--surface-subtle',
  '--surface-tertiary',
  '--text-chat',
  '--text-command',
  '--text-danger',
  '--text-ghost',
  '--text-highlight',
  '--text-link',
  '--text-muted',
  '--text-primary',
  '--text-secondary',
  '--text-success',
  '--text-tertiary',
  '--text-tint',
  '--text-warning',
  '--toggle-track-off',
  '--tooltip-bg',
  '--tooltip-shadow',
  '--warning-tint',
  '--z-base',
  '--z-float',
  '--z-glass',
  '--z-modal',
  '--z-overlay-chrome',
  '--z-overlay-drawer',
  '--z-overlay-float',
  '--z-overlay-modal',
  '--z-overlay-top',
  '--z-overlay-transient',
];
